### ISSUE TITLE
RegistrationViewer with optical flow

### ISSUE THREAD

**Issue by paulshuker** [reillytilbury/coppafish#218]
- `RegistrationViewer` is broken since adding optical flow

**Comment by paulshuker** [comment]
@reillytilbury

**Comment by reillytilbury** [comment]
Fixing this has required changing a lot of stuff and has given me an opportunity to refactor the old registration viewer which was a mess and impossible to debug.

Now, instead of applying transforms at time of viewing to reg images, these are applied before saving reg images which results in a faster viewer.

The methods can also now be seamlessly scrolled through [no registration, optical flow, optical flow + icp] while staying in the same spot which shows how large the shifts are and how far things are off.
![image](https://github.com/reillytilbury/coppafish/assets/88850716/d3533374-bb15-4c67-822d-b869250205e4)


Also added a vector field plotter for the optical flow:
![image](https://github.com/reillytilbury/coppafish/assets/88850716/14c11e14-3e1e-4afe-9ff1-2bffd05a144f)

Just configuring buttons and adding back ICP Viewer, Overlay Viewers, BG Viewers and should be ready by tomorrow.
