### ISSUE TITLE
Viewer Updates

### ISSUE THREAD

**Issue by reillytilbury** [reillytilbury/coppafish#96]
Suggestions by Kenneth today:
1. Viewer should include a help screen detailing which hot keys do what
2. Sometimes when hovering over a spot the gene name is shown and sometimes it is not. It would be nice if it was always shown.
3. Selecting genes can be quite buggy.
4. Having a single 'home' button to revert to the zoomed out home screen would be good.

**Comment by paulshuker** [comment]
1 is in #89 and I just added this to my dev branch :)

**Comment by reillytilbury** [comment]
As per meeting with @kdharris101 today, we should add the following to this list:
5. show the tile that the spot is in when hovering over it
6. separate the view_codes output with some horizontal lines to allow us to more quickly notice good and bad matches

**Comment by kdharris101** [comment]
Instead of point 6 it would be better and sufficient to fix the highlighting of round/channels expected from the bled codes / free codes.  

Not certain what will be best way to do it, but one thought is a circle (not filled) in the middle of each pixel of the code viewer, whose radius corresponds to the bled code intensity.  This could be thresholded so that if the intensity is below 0.1 or so the circle doesn't appear at all.  

Also we could show a circle different color for the free code (by which I mean the bled code scaled by gene efficiency in the current algorithm, or the actual free code once we start using them.)

**Comment by reillytilbury** [comment]
All of these now implemented in my dev, except for the single home button which I found buggy.
